import sender

# https://docs.google.com/spreadsheets/d/1yRAgucahkp8HOmwALUjMGggbeXhbBZB4ZARFKriMdBw/edit#gid=291681891
data = [
    ('Salcedo, Rebeccca', 'Carbon Farming to Sustainable Wool to Garment', 'This project aims to look at how the integration of carbon farming in small scale wool farms displays a shift in cultural values and how that shift in values went on to alter societal actions and our interaction with the natural world. The four colors of the sweater aim to represent the four elements of the carbon cycle; the blue representing water, rain, and the atmosphere, the concrete grey representing the human world, the dark forest green representing vegetation, and the light grey representing the natural wool produced from the cycle. The color mixing sections are meant to display the complex interconnections between the elements of the cycle and show how you may be able to distinguish between the different elements but you cannot separate one from another without deconstructing the entire cycle (or sweater). The cables down the sides are meant to display an additional level of connections within the cycle, how we may be able to see some complexities more easily than others, and how we have to act carefully with natural systems because there are often more complexities than we initially recognize.', '11in x 17 in ', 'Actual sweater made out of wool yarn. Printed picture will be displayed for art show. '),
    ('Wang, Shichun; Wang, Hao; Jin, Mike; Liao, Qitian', 'The Modern Oxbow', 'Our painting is a parody of one of Thomas Cole\'s oil paintings, The Oxbow. In his original painting, the English-born American painter portrays a clash of two sides of America in the 19th century: Wilderness & Danger vs. Civilization & Opportunities. Our version is a remaster of this idea but from the today\'s perspective of international students. We as foreigners also have mixed feelings when coming to the US, where opportunities (left side) abound but risks (right side) also follow. ', '75cm * 50cm * 0', 'Painting paper and Colored markers'),
    ('Pumpkin, Ellie', 'Protecting What I Love: A Guide to Native Plants of the Redwood Forest', 'I created this model plant guide to establish an interface between the native flora of the redwood forest and the people that enter their habitat. My hope is to lessen the disconnect between humans and nature and, ultimately, to encourage the sustainable management of native species and other natural resources. ', '8.5 in x 5.5 in x 1 cm', 'Mixed media. Colored pencil and black ink on paper. Pressed plant samples secured under clear tape. Stapler, printer, ruler. '),
    ('Kim, Christine', 'US Air Quality', 'It\'s a timeline of US Air Quality. There is also a progression in artwork. I go from pencil, to colored pencil to paint.', '28x20in', 'pencils, paint'),
    ('Liang, Justine', 'Life Within Nature', 'My piece hopes to explore the effects and juxtaposition between nature as an open space with the Native Americans with the privatization from the colonists. Here, it shows the re-creation of the gentrification map shown in class with the Mississippi river and the areas around it bounded into the different plots of land that people can acquire which are then also separated into the various smaller plots for the different types of crops. For people viewing this piece, maybe they will draw the connection between industrialization for the betterment of producing agriculture but also see that it creates a divide between nature and humans. "Life Within Nature" expands on the idea of production by commodification and recognize that we are not at one with nature anymore, we are just living within the nature that we decided to divide. ', '20 in x 30 in x 1/2 in', 'I used a foam board and put sewing pins into it to create the grid-like platform for me to wind sewing thread around.'),
    ('Lee, Katniss', 'Exotic Pets of California: True Meaning of Animal and Human Relationship', 'People these days consider their pets as their "family" and show deep love towards them. However, one must question the origins of pets, and how pet industry began through captivating wild animals and forcing them to the human environment. This artwork was inspired by a recent ferret protest of California\'s ferret owners who supported the legalization of ferret owning in the state. They criticized the government for treating such innocent animals as criminals that disrupts California\'s ecosystem. They said they are doing this for their ferrets, but would a ferret want to live in the wild, or with "family"? ', '16 * 10', 'Acrylic Paint'),
    ('Kim, Subin', 'The Missing Parts of US History', 'I noticed that Asian Americans are often omitted in high school US history textbooks, even though they played a big role (especially in California) in terms of economic development, social development, etc. After learning about Asian American history in ESPM 50AC, I started to see the similarities between the ways in which Jews and Asians were treated in their communities as minorities. ', '13 x 9.5 x 1/2', 'White drawing paper, black Sharpie, color pencils, black gel pen, printed pictures'),
    # commented out because generates huge 200mb array of images, manually updated.
    #('Truong, Sarah', 'Alive and Stronger: White Hegemony on Native American Land', 'Native Americans, specifically the Pomo Indians of Northern California, have a long history of tribal displacement and relocation due to white hegemonic practices since the dawn of the first settlers in North America. These past practices include introducing year-round monoculture, grazing animals, westward expansion, the Indian Removal Act, the Dawes Act, and Indian reservations and boarding schools. In the 21st century, white hegemony against Native Americans is still alive and well, which can be seen through current climate change policies and opinions that affect the land and lifestyle of Native Pomo Indians. To depict the consequences from the lack of efforts to combat climate change due to white hegemony, I created a mosaic of a large photo showing the Santa Rosa wildfires, as a result of climate change, affecting and damaging Pomo land in 2017. Each smaller photo within the mosaic illustrates and displays how current climate change opinions and policies with white hegemonic subtleties have caused Native Pomo Indians to feel not only culturally displaced, but also physically displaced from their land.', 'Height: 24 inch, Width: 18 inch', 'Photoshop, Adobe Illustrator, iPhone 7 (for photos I took on my own)'),
    ('Callender, Drake', 'Perception and Deception of the Yellowstone Wolf', 'This art collection is about the ecological impacts that wolves had on the ecosystem in Yellowstone National Park. My goal is to address the perception that humans have on wolves, and how the wolf can be a deceptive figure by its status as a top predator. Each drawing has its own symbolism and through an understanding in the ecological impacts of the wolf in relation to the natural environment and humans,  I hope to represent the beauty and truth that consists of the wolf.', ' 14 in x 17 in  (3 drawings with these dimensions)', ' pencil, colored pencil, and colored pen'),
    ('Wong, Aerial', 'Reclamation', '“Reclamation” depicts a post-human cityscape in the process of being consumed by plant life. This piece explores the opposing forces of nature and society through an abstract representation of human neglect of the environment resulting in the decline of the human race and unrestricted growth of nature. It serves as a reminder of both human impact on the world and nature’s inability to be suppressed.', '12"x 24" x 0.75"', 'Acrylic paint on canvas'),
    ('Iyer, Nandita', 'Wolves in Yellowstone', 'My painting depicts the positive effects of reintroducing wolves into Yellowstone after they were hunted to extinction in the early 1900s. Wolves radically changed the entire ecosystem. I tried to depict more species on the right hand side, and a variety of plant growth.', '9 in x 12 in', 'Watercolors, pen, graphite, and color pencils'),
    ('Kafkaloff, Kristen', 'Unnatural Disaster', 'Although Hurricane Katrina is considered a "natural disaster", the contributing factors to the aftermath involved far more than natural causes. The government, structural racism, economic priorities, etc. played key roles in the resulting disaster. Hurricane Katrina brought critical issues involving racism and government priorities to light.\n\nThis piece is meant to be interactive, so you are encouraged to take out the disks sitting on the inside and look at the numbers on the back corresponding to its risk description!', '7 x 11 x 4 (inches)', 'Watercolor paints, watercolor paper, acrylic paints, paint pens, bakers twine, feathers, corkboard coasters, and a shoebox'),
    ('Lu, Shan; Shi, Chenyu', 'Cultural Integration', 'Geographical surrounding pose significant influence on cultural formation and my roots in Northeastern China have shaped me deeply. This is compounded when I attempt to integrate into culture of Bay Area, where has totally different geography and social landscape from my hometown. I expressed this internal cultural confrontation by exploring the geographical influences imposed by places that I once lived and am currently living. The Hukou Waterfall on the left side is the largest waterfall on the Yellow River, China.  The combination of two different colors of water represents the integration of eastern and western cultures.', 'Not sure', 'We draw this paint on the ipad.'),
    ('Yaghi, Chris', 'Litter is Murder', 'Please realize the different ways that litter can hurt the environment. Now, answer the question, is it worth littering to get rid of some trash that is not effecting you? Enjoy my work. ', 'Its a poster. maybe 12inx24in', 'Colored pencils'),
    ('Thomas, Poloniato; Feinberg, Jason', 'Bay Area 3D Sea Level Rise', 'Here are 3D maps of the San Francisco Bay Area based on a 100-year storm event coupled with different sea level rise scenarios: \n- 0.0m\n- 0.5m\n- 1.0m\n- 1.4m', '8.27 × 11.69 x 3/4 inches', '3D printing, plastic'),
    ('Sun, Ann; Lin, Ying; Tang, Jiahui (Kalie)', 'One Wave, Two Faces ', 'Our piece depicts the duality of the white and black experiences of Hurricane Katrina. On both sides, the same "wave" of the disaster is portrayed, but the corresponding experiences for the two races are very different. On the one side, a white man is being rescued by all the various political, social, and economic advantages his community typically enjoys; whereas on the other side, a black man is being drowned by all the reciprocal disadvantages his community generally suffers. Note the surrounding environment as well: the white man lives in a gentrified and urban neighborhood less affected by the flood, whereas the black man\'s neighborhood is buried beneath the water, but still very clearly culturally-rich, thereby reflecting the vivid and unique social scene (look closely beneath the cellophane!). Think of this as a structural political cartoon! ', '55cmx45cmx30cm', 'Foam board, poster boards, cellophane, Play-Doh, wooden sticks, toothpicks, markers, strings, tape, glue'),
    ('Gallegos, Michael', 'Hamburger Tree', 'Obviously hamburgers don\'t grow on trees and cannot be picked by someone to eat then and there. So where do hamburgers and many other foods that Americans eat come from? Who raises the meat, in what conditions and where and how is the cheese, bread, and lettuce created? Is it from a small local farm or a large corporation? This picture also shows that many American processed foods are easier and cheaper to access than unprocessed foods. How do these food prices in America and the origins of the food you eat impact the environment and social equality?', '9 inches x 12 inches x about 1.5 inches', 'acrylic paint on stretched canvas'),
    ('Xia, Mulan', 'California Water', 'California water history has been turbulent in the past century. While the abundance of this natural resource has enabled California to become the state it is today, its wealth has not always been distributed equally among everyone. I tried to create a visual timeline of key milestones, but in consideration of the space I had to work with, many of the landmarks are not explicitly written; you have to look a little. Observe the gradient of water, and how the water quality appears to decline with the passage of time. I tried to hide little easter eggs throughout (they might\'ve been a too subtle though), so look for them!', '22 in * 34 in * 1 mm ', 'Paper (designed in illustrator), I was going to print it on higher quality poster board but I\'m poor and it was really expensive :('),
    ('Quiroz, Michael', 'Drowning', '"Drowning" is a track that represents the societal resistance to understanding the risks of natural disaster -- particularly, Hurricane Katrina and Climate Change. Rather than focus on how we shape the environment and stand to be affected by it, we often get caught up in more material matters. Through this tendency, we have the potential to "drown." This song maintains this focus while also touching on racial inequalities, police brutality, capitalism/industry in shaping our relations with the climate, and the daily concerns of the consumer. ', 'N/A', 'FL Studio, Blue Yeti microphone, Audiobox USB, Bravo Audio Tube amp, Sennheiser HD 600 headphones.'),
    ('Jung, Jessica', 'Rice Map of Chinese Immigration to America ', 'My project is a representation of Chinese immigration from the Guangdong province in China to the golden state of California. I chose rice to create the majority of the map and used gold glitter specifically for California. This is to represent the transition of material that the Chinese were exposed to when moving to America. The placement of the rice is also a symbol of the tedious work that the Chinese did. Although a grain of rice seems insignificant on its own, when many are stacked together, they become heavy and strong similar to the influence the Chinese had on American history. ', '11 in x 15 in ', 'colored rice and glitter'),
    ('Jain, Divya', 'The [Built] Environment', 'This series was inspired by the aesthetic similarities between natural environments and manmade structures. The photographs were paired to emphasize the analogous forms, lighting, and spatial qualities between nature and architecture, illustrating the way in which architecture mimics nature. This idea of the natural world acting as a precedent for architecture begs the question of why we place such a low monetary value on preserving our national parks, monuments, and other natural sites.', '6 prints, each 11"x14"', 'Digital Photography'),
    ('Chow, Melanie', 'Boom ', 'In 1881, Hercules was established as a company town for the Hercules Powder Company, a chemical and munitions manufacturing company that was known for its specially patented dynamite called Hercules, named after the greek mythological hero for being so powerful. Its remote location at the time as well as its proximity to the Central Pacific Railroad and San Pablo Bay led this city to be the company\'s ideal location for the production of explosives. A majority of those working under these dangerous conditions were Chinese laborers, who often faced discrimination from their white employers. \nThe City of Hercules has greatly changed from what it once was; today the suburban commuter city is home to a ethnically diverse population of approximately 25,000. ', '9 x12', 'Watercolor and Ink '),
    ('Andres, Jerome', 'Filipino Woodwork: Connecting Past to Present', 'This project aims to symbolize the general progression of the use of natural resources in the Philippines as well as provide an accurate representation of tools and structures. I chose to work with wood as it is one of the most widely used resources across cultures and time, and I wanted to show how, though Filipinos\' relationship with nature is changing, there is still a significant influence from the past. All three of these art pieces (fishing rod, wind turbine, and Filipino hut) attempt to stay true to the actual design while incorporating resources that would not have been available in older times, symbolizing the natural change in tool and shelter building as time has passed. Please see the art descriptions accompanying each art piece for more details.', 'Fishing Rod: 7 ft height, width and depth negligible; Windmill: 12" x 5" x 5"; Hut: 12" x 30" x 24"', 'I mostly used wood purchased from local hardware stores. I mainly used a saw and my father\'s traditional itak (bolo knife) as tools to make the art. For the hut, I used a glue gun for structural support as using the traditional hammer and nail method was unfeasible given the small size of the model. The fishing rod uses a long bamboo stick and modern fishing equipment such as a hook, weight, and fishing line. For the wind turbine, I used a drill and screwdriver as the piece utilizes more modern screws, nuts, and bolts.'),
    ('Galeas, Joselvin ', 'The Corn Mother ', 'In front of you is my portrayal of The Corn Mother— the central figure in a Native American myth that describes the origin of corn. One version of the myth describes the sprouting of corn from the places where a woman’s corpse, that of The Corn Mother’s, is dragged (by some accounts, She gave consent to be killed). Via Her death was She able to feed a hungry tribe.  ', '8 x 3.5 x 3.5”', 'Self-Hardening '),
    ('Kim, Ashley; Jung, Amy', 'Archaic but Displaced', 'Gentrification in the Mission District of San Francisco is an ongoing process. However, the social clashes it creates is as blatant as the striking differences one sees of the infrastructure on the streets. Yoga classes held next to a family-owned grocery store. Nicely-dressed "hipster" tourists passing by the run-down barber shop. These juxtapositions represent the struggles that native residents face as their neighborhood disappears before their eyes due to skyrocketing rent prices, decreasing wage labor, and increasing evictions. ', '14 x 16 and a photo album', 'cotton board, paper, ink, glue '),
    ('Le, Anh', 'The harvest', 'The painting depicts the agricultural system of some Native American tribes. There\'s an illustration of Mother Corn granting the essential food to the natives, which consists of the Three Sisters (corn, bean, squash).', '11 x 17 inches', 'Soft pastel'),
    ('Solorio, Leonel', 'The Second Yácata ', 'In the late 1520s, in what is now the state of Michoacán, Mexico, Spanish Conquistadors plundered Tzintzuntan, the capital of the Indigenous Purepechan Empire, despite the fact that the Purepechan Emperor had surrendered peacefully. They raided the five Yácata pyramids, which were used by the Purepecha People for religious ceremonies, and used their stone and wood infrastructure to build their own Christian monasteries. To honor my Indigenous ancestors, I recreated the second Yácata pyramid, which unfortunately was the most destroyed of the whole five,  cutting the shape of the pyramid out of cork board to mimic the rough stone slabs and religious inscriptions that once decorated the Yácata. I painted the base light green to mimic the jungle hillside that the Yácatas were built into, and I left the top of the Yácata unpainted to represent the wooden temple that once sat upon the pyramid, where various ceremonies, sacrifices, and burials were held.', '12 in x 12 in x 4 in ', 'The overall base is a canvas board, and the temple itself made of cork boards, adhesives, and acrylic paints. '),
    ('Hassanin, Samir; Mitchell, Narumi', 'Rumsen Creation Tale', 'This is our interpretation of the Ohlone tribe\'s Rumsen myth. The four main characters are by a river bed, shortly after the world has stopped flooding. In order to repopulate the earth, the coyote must follow the instruction of the eagle, so that he may be the father of humanity. \n\nIn this depiction of an Ohlone creation story, Rumsen, we included the main characters: The woman, coyote, eagle, and hummingbird. In this story, after the eagle has sent the coyote down to see if the earth was dry, he gives him the task of repopulating the earth with the woman. In this painting we show the scene where she picks a louse from the coyote\'s back which impregnates her. The background is based on Pico Blanco, and the aura around the characters represents the connection the natives had with nature. ', '14"x12"x1"', 'Acrylic on canvas'),
    ('Arputhasamy, Cyrene; Tan, Timothy', 'Bison Hunt', 'The American Bison experienced a swift decline in population size in the late nineteenth century due to habitat loss by westward expansion and bison hunting parties. While the Native Americans relied on bison as a primary food source, non-indigenous people hunted the species for sport and simply left them dead on the prairies. This forced Native Americans to be more compliant in relocating to reservations because of their dependency on the US government for a new food source. Buffalo also served an important ecological role of cultivating the prairies which allowed the growth of a diverse range of native plants and the loss of such plants is thought to be a contributing factor to the dust bowl in the early twentieth century. Illustrated on the left is a grazing buffalo in a thriving prairie, and on the right is a hunted buffalo in a dry prairie with dust clouds forming in the back. ', '12" x 16" x 1" ', 'acrylic paint'),
    ('Choy, Junghyun', 'Drought in California', 'This infographic map pinpoints some locations that were affected by or are related to California\'s most recent drought. The goal was to convey some key events or highlights in a visual way while implying how important water is as a natural resource. Additionally, the variety of visual details was to show that information can come in many ways. ', '11 x 8.5 (paper)', 'Paper, Adobe Illustrator'),
    ('Ortiz, Isabel Xilonen', 'environmental consonance', 'This painting is based on interviews I conducted over the course of a week, with six people who grew up in Santa Ana, CA, and identify as children of Mexican immigrants. We discussed their environmental perspectives and practices in the context of their cultural backgrounds, identities, and experiences growing up in Orange County. From these testimonies I have noticed there is a significant disconnect in Santa Ana from the traditional Mexican ecological knowledge that was so prevalent only a few generations ago. I hope that with this painting I can illustrate what it means to grow up with the unique environmental worldview of a person who has experienced the dynamic process of cultural adaptation. This adaptation can be represented as nonlinear movement involving a cultural  synthesis of immigration history with adaptation to mainstream ideology.', '12 x 12 x 1 inches', 'acrylic on canvas'),
    ('Pariser, Isaac', 'Panamint City: A Ghost Town Lost in Time', 'Nestled in a valley in the Panamint Mountain Range, Panamint City was once a bustling town during the California Gold Rush. In 1876, a flash flood roared through the valley and washed out most of the town. Though numerous attempts have been made to reestablish mining operations, in 1983, another flash flood wiped away roads to the bedrock, making the city permanently inaccessible to vehicles. In spring 2018, I backpacked to the ghost town and cataloged its current condition. I hope that by viewing these pictures, people think about the fragility of human settlement classical conflict of "man versus nature". ', '9  (5 x 7.5 ) size photos', 'Card stock. '),
    ('Truong, Lilianna', 'The Veiled Identity', 'Being faced with decades of continuous stereotypes and misconceptions, the Native American identity has been warped and lost. Influences of media, social activism and other forms of American perception have all lead to the false representation of people with rich history, knowledge, and complexity.', '8 in x 13 in x 1in', 'Acetate, foamcore, oil based marker'),
    ('Nguyen, Emily', 'Capitalism, Environmentalism, and Racism', 'A broad depiction of the dynamic between racism against African Americans, environmentalism, and capitalism.', '17 x 10 x 1.5', 'Resin, embroidery thread, wood'),
    ('D’Ambrogia, Kelly', 'The Urban Tree', 'This tree is a depiction of the effects of urbanization on the natural environment. Urbanization often leads to a loss of natural habitats, deforestation, and pollution. I made ropes out of plastic bags, which are wrapped around the tree to symbolize the effects of pollution and loss of natural areas. The butterflies are made out of soda cans, and the flowers are made out of plastic bottles, to represent how nature and urban areas are sometimes able to coexist, despite negative impacts. The base is made of recycled paper which I painted over with watercolors to create the grass. ', '7 x 3 x 2', 'Branches, plastic bags, soda cans, plastic bottles, recycled paper, watercolors, sharpies'),
    ('Lew, Dylan; Adachi, Mei', 'Water Crisis Incarnate', 'Our art project is on the topic of Flint Water Crisis. The project will portray three different perspectives surrounding the crisis by highlighting key figures that were involved in this public health crisis, namely the guilty parties, affected parties and activists. We created three portraits with various photoshop technique applied, and the artistic objective of this artwork is to show the correlation between social and environmental aspect of the Flint water crisis and the magnitude to which the crisis impacted people of Flint. Through this we are addressing for environmental justice. ', '11 in. x 27.5 in ', 'Matte paper print'),
    ('Sosa, Diana', 'Gentrification in Oakland ', 'In my art, I decided to illustrate and use the symbol of yin and yang to demonstrate how gentrification is affecting Oakland. I wanted to create a visual representation of the "good" and the "bad" side side of gentrification and who is getting affected and benefiting from this. I wanted to illustrate this through a series of drawing and illustrations without many words being involved. I decided to illustrate this be creating like each side in the case of how people of color are being affected on the left side and how white people are benefiting on the right side. ', 'It\'s a poster so the height is 24in and the width is 17.625. Ideally the final product should not change drastically. ', 'Used programs of Adobe Photoshop and Illustrator to create and put these images together. '),
    ('Reyes, Teodora; Bermundez, Christal', 'Pieces of Oakland', '', '', ''),
    ('Chan, Crystal ', 'Behind', 'This dance piece is inspired by the story of immigration to the United States in the 19th century. Specifically, this piece shows three segments of immigration: leaving your home country and loved ones, journeying to a foreign country without knowing what is in store for you, and finally being used as cheap labor in America to build the transcontinental railroad and many other things. ', 'Dance video', 'Dance video'),
    ('Ortiz, William', 'More than Just a Dumb Fish', 'Growing up in the Central Valley, I constantly heard about the Delta Smelt. With these four images, I hope to display some of the arguments in this controversy and point the ridiculous nature of some.', '8.5in x 11in (4 pieces of same dimensions)', 'Bristol board, pencil, ink.'),
    ('Westin, Emma', 'Hopi Coiled Basket Plague ', 'This is a coiled basket plague in the style of the Native American tribe Hopi. Basket weaving has been an important part of the Hopi culture for many centuries, and the coiling technique applied to make this basket was one of three main methods they used while weaving. ', '3" x 10" x 10" ', 'Yarn. Rope.'),
    ('Lee, Natlie', 'Out of Sight, Out of Mind', 'I know who I am—a proud Asian American. But why was I so blind to the suffering of my own people who poured their blood, sweat, and tears into this land so I can proudly stand where I am today? \n\nWhy is our past forgotten? Why is our presence erased by the media  in the present? Why is our future so uncertain?', '14x17', 'watercolor, soft pastels, graphite pencil set'),
    ('Anselmo, Dylan', 'Where is our water?', 'I chose to illustrate the reality of where our water comes from. Learning about where California water actually comes from it inspired me to illustrate water in geometric lines and shapes. Because how we gather water now is more mechanical and separated from nature illustrated by the dam encompassing the circle and with the mountain. The circle containing the mountain represents the the picturesque ideal we have about where we think we get our water from and how it is separated from the reality of how we actually gather water. The bottom represents where a majority of our water goes which is municipal and agricultural but how the plants are wilted and the buildings are incomplete because at the level of water we are using in California could be dwindling unless we make changes to responsibly use our finite resources. ', '11x17 in', 'printed poster'),
    ('Zia, Yumna', 'A Flower Among Weeds', 'San Jose\'s horizon shows an amalgam of urban, suburban, and rural landscapes, which is representative of the various stages of San Jose\'s history. Described upon first sight as "The Valley of Heart\'s Desire," San Jose has started out as open mountains and fields. Over time the city was dominated by fruit orchards as canneries became a lucrative business rooted in San Jose. Soon, the majority of San Jose population settled in the center of the valley, what is known as downtown. At the center of San Jose rising tall buildings that make up its urban environment. However, the Mt Diablo mountain range still surrounds the center of this million-member city, while suburbs grow by the borders. San Jose stretches as far as the eye can see from some of its beautiful vista points. I painted this to display San Jose\'s dynamic landscape, which preserved its roots in nature even as the city grew and changed over time. Though its population grows at an increasing rate at the center of Silicon Valley, San Jose still possesses growing woods, clear mountains, hiking trails, and an abundance of wildlife.', '14"X17"', 'watercolor on paper'),
    ('Cartier, Abby', 'For All, For No One', 'A portrayal of the Klamath River ecosystem, with attention to important plants and animals to the Yurok tribe. The title addresses the different views of nature that have imparted on the same land in the form of property rights.Meaning, in the Yurok property rights system: all the richness of the ecosystem is for all to enjoy, but it is no one person\'s alone. ', '11 in. x 15 in. flat', 'marker and watercolor on paper'),
    # ADDED
    ('Randmaa, Jack', '[untitled sketches of San Francisco]', None, 'ink and watercolor'),
    ('Yang, Jonathan; Chen, Luming; Ma, Lynn; Chen, Percival', 'Dialectical Face', '22 in x 34 in', 'digital and collage'),
    ('Yuan, Yidan', 'Past and Present', None, 'digial'),
]

pieces = [
    dict(zip([ 'authors', 'title', 'desc', 'size', 'medium' ], row))
    for row in data
]

if __name__ == '__main__':
    sender.send_data(
        pieces=pieces,
        box_input_folder_id='57395093689',
        collection_name='sp18_0',
        semester_tag='sp18')
